//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalization
    {
        public int Id { get; set; }
        public int PationtId { get; set; }
        public string Code { get; set; }
        public System.DateTime Data { get; set; }
        public string Diagnosis { get; set; }
        public string Goal { get; set; }
        public string Department { get; set; }
        public int ConditionsId { get; set; }
        public int Time { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Decline { get; set; }
    
        public virtual Conditions Conditions { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
