//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEvents
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Result { get; set; }
        public string Recommendations { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
